# The settings are inherited from common repository repo-settings (same file name and location)
# You can append settings that are deeply-merged with the inherited settings.
#
# When you have installed the GitHub App "repo-settings" in this repository,
# any change of this settings.yml file is detected by the GitHub App and
# the settings of this repository are updated immediately.

_extends: repo-settings:.github/common-settings-v2.yml

# repo specific settings
repository:
  name: terraform-ibm-landing-zone
  description: "Creates a fully customizable VPC environment and compute resources (VSI, Red Hat OpenShift) with presets designed to meet strict compliance needs."
  topics: core-team, ibm-cloud, landing-zone, secure-landing-zone, slz, status-graduated, terraform, terraform-module, module-type-3
