name: Release-Pipeline

permissions:
  contents: write
  issues: write

# Trigger on push(merge) to main branch
on:
  push:
    branches:
      - main

jobs:
  call-terraform-release-pipeline:
    uses: terraform-ibm-modules/common-pipeline-assets/.github/workflows/common-release.yml@v1.24.2
    secrets: inherit
