name: Release-Pipeline

# Trigger on push(merge) to main branch
on:
  push:
    branches:
      - main

jobs:
  call-terraform-release-pipeline:
    uses: terraform-ibm-modules/common-pipeline-assets/.github/workflows/common-release.yml@v1.20.0
    secrets: inherit
